server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB_NAME:shift}
    username: ${POSTGRES_USERNAME:shift}
    password: ${POSTGRES_PASSWORD:shift}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - sales_management
  jpa:
    show-sql: true
