server:
  port: 2525
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - sales_management
    clean-on-validation-error: true


  jpa:
    show-sql: true
